apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem
