apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 6767
    protocol: TCP
    targetPort: http
  selector:
    app: bazarr
    release: bazarr
  type: ClusterIP