apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
      release: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        release: jellyfin
    spec:
      containers:
      - image: linuxserver/jellyfin:latest
        imagePullPolicy: Always
        name: jellyfin

        # Bit of a security concern since application is externally available
        securityContext:
          privileged: true

        ports:
        - containerPort: 8096
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data/shows
          name: shows
        - mountPath: /data/movies
          name: movies
        - mountPath: /dev/dri/card1
          name: card
        - mountPath: /dev/dri/renderD128
          name: renderer
      restartPolicy: Always
      nodeName: mackey
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin
      - name: shows
        nfs:
          server: 192.168.100.40
          path: /volume1/Media/Shows
      - name: movies
        nfs:
          server: 192.168.100.40
          path: /volume1/Media/Movies
      
      # Ensure device has rwx perms for other users on host (chmod -R o+rwx /dev/drive/card1)
      - name: card
        hostPath:
          path: /dev/dri/card1
      - name: renderer
        hostPath:
          path: /dev/dri/renderD128