apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
      release: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        release: jellyfin
    spec:
      containers:
      - image: linuxserver/jellyfin:latest
        imagePullPolicy: Always
        name: jellyfin
        ports:
        - containerPort: 8096
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data/shows
          name: shows
        - mountPath: /data/movies
          name: movies
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin
      - name: shows
        nfs:
          server: vault.storage.vandeneede.org
          path: /mnt/PvtPool/Media/Shows
      - name: movies
        nfs:
          server: vault.storage.vandeneede.org
          path: /mnt/PvtPool/Media/Movies