apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
      release: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        release: jellyfin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardware
                operator: In
                values:
                - southpark
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - qbittorrent
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: linuxserver/jellyfin:latest
        imagePullPolicy: Always
        name: jellyfin
        ports:
        - containerPort: 8096
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data/shows
          name: shows
        - mountPath: /data/movies
          name: movies
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin
      - name: shows
        nfs:
          server: 192.168.100.41
          path: /volume1/Media/Shows
      - name: movies
        nfs:
          server: 192.168.100.41
          path: /volume1/Media/Movies