apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: jellyfin
    release: jellyfin
  type: ClusterIP