apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem