apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: immich-redis
      release: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
        release: immich-redis
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        # --- General ---
      - image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
        imagePullPolicy: Always
        name: immich-redis
        # ---------------
        # --- Network ---
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        # ---------------