apiVersion: v1
kind: Service
metadata:
  name: homarr
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 2283
    protocol: TCP
    targetPort: http
  selector:
    app: immich
    release: immich
  type: ClusterIP