apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: clusterstorage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: clusterstorage
  volumeMode: Filesystem
