apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem