apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamystats-nextjs
spec:
  selector:
    matchLabels:
      app: streamystats-nextjs
      release: streamystats-nextjs
  template:
    metadata:
      labels:
        app: streamystats-nextjs
        release: streamystats-nextjs
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        # --- General ---
        - image: ghcr.io/fredrikburmester/streamystats-nextjs:v2.18.1
          imagePullPolicy: IfNotPresent
          name: streamystats-nextjs

          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: streamystats
                  key: database
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: streamystats
                  key: session-secret
            - name: NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: streamystats
                  key: next-server-actions-encryption-key
            - name: HOSTNAME
              value: 0.0.0.0
            - name: JOB_SERVER_URL
              value: http://streamystats-jobserver.streamystats.svc.cluster.local:3005

          # ---------------

          # --- Network ---
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          # ---------------
