apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: esphome
    release: esphome
  type: ClusterIP