apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    release: mongo
  annotations:
    metallb.io/loadBalancerIPs: 10.71.0.12
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    app: mongo
    release: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
spec:
  clusterIP: None
  selector:
    app: mongo
    release: mongo