image:
  repository: louislam/uptime-kuma
  tag:
  pullPolicy: Always

env:
  TZ: UTC
  UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik-internal
    hosts:
      -
        host: uptime.vandeneede.org
        paths:
          -
            path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /app/data
    readOnly: false
    storageClass: clusterstorage
    accessMode: ReadWriteMany
    size: 2Gi
    retain: true

dnsConfig:
  nameservers:
  - 192.168.100.52