apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
