apiVersion: v1
kind: Service
metadata:
  name: jellystat
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: jellystat
    release: jellystat
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jellystat-db
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: pg
    port: 5432
    protocol: TCP
    targetPort: pg
  selector:
    app: jellystat-db
    release: jellystat-db
  type: ClusterIP