apiVersion: v1
kind: Service
metadata:
  name: moonraker
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 7125
    protocol: TCP
    targetPort: http
  selector:
    app: moonraker
    release: moonraker
  type: ClusterIP