apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vandeneede-production-cert
  namespace: default
spec:
  secretName: vandeneede-org-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.vandeneede.org"
  dnsNames:
  - "vandeneede.org"
  - "*.vandeneede.org"