apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vandeneede-staging-cert
  namespace: default
spec:
  secretName: vandeneede-org-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.vandeneede.org"
  dnsNames:
  - "vandeneede.org"
  - "*.vandeneede.org"