apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.0.187
  clusterIPs:
  - 10.43.0.187
  externalTrafficPolicy: Local
  healthCheckNodePort: 31234
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    nodePort: 30988
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
    release: pihole
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.100.52
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.113.154
  clusterIPs:
  - 10.43.113.154
  externalTrafficPolicy: Local
  healthCheckNodePort: 31703
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns-udp
    nodePort: 31138
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: pihole
    release: pihole
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.100.52
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  clusterIP: 10.43.238.117
  clusterIPs:
  - 10.43.238.117
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: pihole
    release: pihole
  sessionAffinity: None
  type: ClusterIP