apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitpro
spec:
  selector:
    matchLabels:
      app: splitpro
      release: splitpro
  template:
    metadata:
      labels:
        app: splitpro
        release: splitpro
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: splitpro
          image: ossapps/splitpro:latest
          imagePullPolicy: Always
          
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          ports:
            - name: splitpro
              containerPort: 3000
              protocol: TCP

          volumeMounts:
            - name: data
              mountPath: /app/uploads

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: splitpro-secrets
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splitpro-secrets
                  key: db-password
            - name: POSTGRES_DB
              value: splitpro
            - name: POSTGRES_PORT
              value: "5432"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: splitpro-secrets
                  key: db-url
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: splitpro-secrets
                  key: nextauth-secret
            - name: NEXTAUTH_URL
              value: https://splitpro.vandeneede.org
            - name: FROM_EMAIL
              value: systems@vandeneede.org
            - name: EMAIL_SERVER_HOST
              value: smtp.protonmail.ch
            - name: EMAIL_SERVER_PORT
              value: "587"
            - name: EMAIL_SERVER_USER
              valueFrom:
                secretKeyRef:
                  name: splitpro-secrets
                  key: smtp-user
            - name: EMAIL_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splitpro-secrets
                  key: smtp-password
            - name: DISABLE_EMAIL_SIGNUP
              value: "true"

          readinessProbe:
            failureThreshold: 6
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 5
            httpGet:
              scheme: HTTP
              port: 3000
              path: /
          livenessProbe:
            failureThreshold: 6
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 5
            tcpSocket:
              port: 3000

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: splitpro-data