kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 2.0.14
    helm.sh/chart: mosquitto-4.8.2
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "clusterstorage"