apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-vc
  namespace: bitwarden
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: clusterstorage
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi