machine:
  network:
    interfaces:
      - interface: eth0
        dhcp: false
        vlans:
          - vlanId: 70 # VLAN for cluster traffic
            dhcp: true
          - vlanId: 71 # VLAN for local ingress traffic
            dhcp: false
          - vlanId: 72 # VLAN for external ingress traffic
            dhcp: false
  kubelet:
    nodeIP:
      validSubnets:
        - 10.70.0.0/24
  install:
    disk: /dev/sda
    image: factory.talos.dev/nocloud-installer-secureboot/ef4cc080b257a0f42c868da1c889990319f5244024c6e710a7211779ef5989ba:v1.13.0
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: kube002.vandeneede.org