apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-internal
  name: unifi
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`unifi.vandeneede.org`)
    services:
    - name: unifi-web
      port: 8443
      scheme: https