apiVersion: v1
kind: Service
metadata:
  name: homarr
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 7575
    protocol: TCP
    targetPort: http
  selector:
    app: homarr
    release: homarr
  type: ClusterIP