apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backupvault-production-cert
spec:
  secretName: backupvault-vandeneede-org-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "web.backupvault.vandeneede.org"
  dnsNames:
  - "web.backupvault.vandeneede.org"