apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: zigbee2mqtt
    release: zigbee2mqtt
  type: ClusterIP