image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: Always

env:
  TZ: UTC

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik-internal
    hosts:
      -
        host: dashboard.vandeneede.org
        paths:
          -
            path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /www/assets
    readOnly: false
    storageClass: clusterstorage
    accessMode: ReadWriteMany
    size: 1Gi
    retain: true