apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: prometheus
    release: prometheus
  type: ClusterIP