apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: sonarr
    release: sonarr
  type: ClusterIP