apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 1880
    protocol: TCP
    targetPort: http
  selector:
    app: node-red
    release: node-red
  type: ClusterIP