image:
  repository: nodered/node-red
  tag: latest
  pullPolicy: Always

env:
  TZ: UTC

service:
  main:
    ports:
      http:
        port: 1880

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik-internal
    hosts:
      -
        host: nodered-werktditnog.vandeneede.org
        paths:
          -
            path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /data
    readOnly: false
    storageClass: clusterstorage
    accessMode: ReadWriteMany
    size: 2Gi
    retain: true