apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: clusterstorage
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
