apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: jellyseerr
    release: jellyseerr
  type: ClusterIP