apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
spec:
  ingressClassName: internal
  rules:
  - host: zigbee.vandeneede.org
    http:
      paths:
      - backend:
          service:
            name: zigbee2mqtt
            port:
              name: http
        path: /
        pathType: ImplementationSpecific