apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-internal
  name: southpark
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`southpark.vandeneede.org`)
    services:
    - name: southpark
      port: 8006
      scheme: https