apiVersion: v1
kind: Service
metadata:
  name: tdarr
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8265
    protocol: TCP
    targetPort: http
  selector:
    app: tdarr
    release: tdarr
  type: ClusterIP