apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splitpro-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splitpro-postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem