apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: prowlarr
    release: prowlarr
  type: ClusterIP