apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: clusterstorage
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
